/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ExtractionToolbarExtractionToolbar: typeof import('./../components/ExtractionToolbar/ExtractionToolbar.vue')['default']
    ExtractionToolbarToolIcon: typeof import('./../components/ExtractionToolbar/ToolIcon.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    HistoryMapHistoryMap: typeof import('./../components/HistoryMap/HistoryMap.vue')['default']
    HistoryMapNodesHmPageNode: typeof import('./../components/HistoryMap/nodes/HmPageNode.vue')['default']
    HistoryMapNodesHmPageNodeToolbar: typeof import('./../components/HistoryMap/nodes/HmPageNodeToolbar.vue')['default']
    HistoryMapNodesToolbarIcon: typeof import('./../components/HistoryMap/nodes/Toolbar/Icon.vue')['default']
    HistoryMapNodesToolbarToolRemove: typeof import('./../components/HistoryMap/nodes/Toolbar/ToolRemove.vue')['default']
    IPhListHeart: typeof import('~icons/ph/list-heart')['default']
    IPhPresentationChart: typeof import('~icons/ph/presentation-chart')['default']
    IPhRocketLaunch: typeof import('~icons/ph/rocket-launch')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionList: typeof import('./../components/SessionList.vue')['default']
  }
}
